SELECT 
DISTINCT
BLOCK_HASH,
BLOCK_NUMBER,
BLOCK_TIMESTAMP,
TX_HASH,
tx_position,
FROM_ADDRESS,
TO_ADDRESS,
ORIGIN_FUNCTION_SIGNATURE,
INPUT_DATA
FROM ethereum.core.fact_transactions
WHERE TX_SUCCEEDED = TRUE
AND TO_ADDRESS = '0xe592427a0aece92de3edee1f18e0157c05861564'
AND ORIGIN_FUNCTION_SIGNATURE = '{function_signature}'
AND BLOCK_TIMESTAMP >= DATEADD(Year, -5, '2025-01-01')
AND BLOCK_NUMBER >= {block_number}